spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mufc3206
    url: jdbc:mysql://127.0.0.1:3306/hongmarket?characterEncoding=utf-8&useSSL=false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
